//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Asset/ControlScheme.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlScheme : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlScheme()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlScheme"",
    ""maps"": [
        {
            ""name"": ""Basic"",
            ""id"": ""df1029f7-ae60-4837-a794-d96a797ed78a"",
            ""actions"": [
                {
                    ""name"": ""ShowSelector"",
                    ""type"": ""Button"",
                    ""id"": ""41ec1432-e2dd-4d29-bc4c-c48f807491e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""54c447e8-f163-4218-8850-3c0ae94f1604"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickHold"",
                    ""type"": ""Button"",
                    ""id"": ""1967758f-a89a-4044-b716-275682ef0611"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""fffe06fc-c7a5-4a91-b317-41ace6f33246"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Deselect"",
                    ""type"": ""Button"",
                    ""id"": ""d4840d5f-6ab4-4a68-af18-22840bca55ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CreateTeamOne"",
                    ""type"": ""Button"",
                    ""id"": ""2be6f56a-d675-4b3b-90a2-318563291e12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CreateTeamTwo"",
                    ""type"": ""Button"",
                    ""id"": ""998ea44f-73f5-4831-98ce-edb536cf5a3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CreateTeamThree"",
                    ""type"": ""Button"",
                    ""id"": ""da89a663-a58a-439e-9e5f-199e8451e4c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CreateTeamFour"",
                    ""type"": ""Button"",
                    ""id"": ""c4917f76-7f2c-4850-88a6-295defdbb00b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CreateTeamFive"",
                    ""type"": ""Button"",
                    ""id"": ""affe17c5-769f-4daf-8286-165b1708e2d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectTeamOne"",
                    ""type"": ""Button"",
                    ""id"": ""abbf4961-8bc3-47d7-b5c5-ad54f4c93295"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectTeamTwo"",
                    ""type"": ""Button"",
                    ""id"": ""cb7948e0-6212-46ba-a773-92feb067e8cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectTeamThree"",
                    ""type"": ""Button"",
                    ""id"": ""b8e175b9-f376-4cb0-bd71-b0897976acce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectTeamFour"",
                    ""type"": ""Button"",
                    ""id"": ""948cecc5-53c5-40e8-8d00-8dda2bcbc0da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectTeamFive"",
                    ""type"": ""Button"",
                    ""id"": ""2822a0a8-4fd8-41a7-9b62-c093176e42c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c139360d-b64e-435c-8fd8-1a76ca9a1af2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89e09687-eece-486d-aa65-99895f13104d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowSelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28551f57-85f2-4269-a0f9-e589682ca345"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6017abb-df81-4f02-82ab-16b982f8756c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold(duration=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""abb051a4-3d84-4838-b124-48a331cbef9c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""38d98b1e-9418-4adf-a81c-addba9da2a05"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e075f093-e83b-45e9-b72d-b32b941fd497"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""cc6afda4-379b-45e8-91dd-e0f195ebde04"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""84e6ced4-4ddb-4113-86ff-6cc3d2a49a8a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9414a8ed-d863-4a1d-ad25-3ea01f1b9f7c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""CreateF1"",
                    ""id"": ""364fc747-eece-4054-a56d-c1d1be59a9ac"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamOne"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""d60a0ba3-a68a-4e40-bdaa-0fc2e42ab9ab"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""50bba066-f9d9-4b75-ba89-21ab3ea9b8ad"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""CreateF2"",
                    ""id"": ""268ac4ce-fb71-4a84-a430-ea69aac99346"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamTwo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""60d9e1ed-723b-482c-a04c-d1994bc417b4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""809083d2-d659-4aed-80e7-1dcdc32e4535"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""CreateF3"",
                    ""id"": ""b9a2a921-f259-472d-a873-cb161eda61c3"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamThree"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""1372642c-cdfd-449d-bbf2-0f4b13803b1e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""000d452f-908c-4356-8609-d36bb7efd842"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""CreateF4"",
                    ""id"": ""350ff97d-8175-4349-857c-1408306d076b"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFour"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""d63e8d32-4fcf-4d80-94a5-c9d8baf35302"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""dcc87959-21cf-4c21-a9c0-88a8ffe628a9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""CreateF5"",
                    ""id"": ""13026700-ac3a-425f-91ef-4d095ef96adf"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFive"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""7013291c-3da3-438a-a965-13d3649386ba"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""9e209588-8277-4825-8cb4-1072bb8e30de"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateTeamFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""780e241c-74d4-4da9-80d0-af66418bb967"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTeamOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9df8b0e8-6582-4950-8b7a-637bc0273bc5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTeamTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ea59d5f-a395-4a34-811b-92bc4978d240"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTeamThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3343236b-6dd4-40af-be5e-e14bcbc980b5"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTeamFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""222ef0b1-9db3-40c7-889d-bb686b71d6a6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTeamFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""680f9357-29b6-4ae4-b264-269f8482d7fb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Basic
        m_Basic = asset.FindActionMap("Basic", throwIfNotFound: true);
        m_Basic_ShowSelector = m_Basic.FindAction("ShowSelector", throwIfNotFound: true);
        m_Basic_Click = m_Basic.FindAction("Click", throwIfNotFound: true);
        m_Basic_ClickHold = m_Basic.FindAction("ClickHold", throwIfNotFound: true);
        m_Basic_Move = m_Basic.FindAction("Move", throwIfNotFound: true);
        m_Basic_Deselect = m_Basic.FindAction("Deselect", throwIfNotFound: true);
        m_Basic_CreateTeamOne = m_Basic.FindAction("CreateTeamOne", throwIfNotFound: true);
        m_Basic_CreateTeamTwo = m_Basic.FindAction("CreateTeamTwo", throwIfNotFound: true);
        m_Basic_CreateTeamThree = m_Basic.FindAction("CreateTeamThree", throwIfNotFound: true);
        m_Basic_CreateTeamFour = m_Basic.FindAction("CreateTeamFour", throwIfNotFound: true);
        m_Basic_CreateTeamFive = m_Basic.FindAction("CreateTeamFive", throwIfNotFound: true);
        m_Basic_SelectTeamOne = m_Basic.FindAction("SelectTeamOne", throwIfNotFound: true);
        m_Basic_SelectTeamTwo = m_Basic.FindAction("SelectTeamTwo", throwIfNotFound: true);
        m_Basic_SelectTeamThree = m_Basic.FindAction("SelectTeamThree", throwIfNotFound: true);
        m_Basic_SelectTeamFour = m_Basic.FindAction("SelectTeamFour", throwIfNotFound: true);
        m_Basic_SelectTeamFive = m_Basic.FindAction("SelectTeamFive", throwIfNotFound: true);
        m_Basic_Pause = m_Basic.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Basic
    private readonly InputActionMap m_Basic;
    private IBasicActions m_BasicActionsCallbackInterface;
    private readonly InputAction m_Basic_ShowSelector;
    private readonly InputAction m_Basic_Click;
    private readonly InputAction m_Basic_ClickHold;
    private readonly InputAction m_Basic_Move;
    private readonly InputAction m_Basic_Deselect;
    private readonly InputAction m_Basic_CreateTeamOne;
    private readonly InputAction m_Basic_CreateTeamTwo;
    private readonly InputAction m_Basic_CreateTeamThree;
    private readonly InputAction m_Basic_CreateTeamFour;
    private readonly InputAction m_Basic_CreateTeamFive;
    private readonly InputAction m_Basic_SelectTeamOne;
    private readonly InputAction m_Basic_SelectTeamTwo;
    private readonly InputAction m_Basic_SelectTeamThree;
    private readonly InputAction m_Basic_SelectTeamFour;
    private readonly InputAction m_Basic_SelectTeamFive;
    private readonly InputAction m_Basic_Pause;
    public struct BasicActions
    {
        private @ControlScheme m_Wrapper;
        public BasicActions(@ControlScheme wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShowSelector => m_Wrapper.m_Basic_ShowSelector;
        public InputAction @Click => m_Wrapper.m_Basic_Click;
        public InputAction @ClickHold => m_Wrapper.m_Basic_ClickHold;
        public InputAction @Move => m_Wrapper.m_Basic_Move;
        public InputAction @Deselect => m_Wrapper.m_Basic_Deselect;
        public InputAction @CreateTeamOne => m_Wrapper.m_Basic_CreateTeamOne;
        public InputAction @CreateTeamTwo => m_Wrapper.m_Basic_CreateTeamTwo;
        public InputAction @CreateTeamThree => m_Wrapper.m_Basic_CreateTeamThree;
        public InputAction @CreateTeamFour => m_Wrapper.m_Basic_CreateTeamFour;
        public InputAction @CreateTeamFive => m_Wrapper.m_Basic_CreateTeamFive;
        public InputAction @SelectTeamOne => m_Wrapper.m_Basic_SelectTeamOne;
        public InputAction @SelectTeamTwo => m_Wrapper.m_Basic_SelectTeamTwo;
        public InputAction @SelectTeamThree => m_Wrapper.m_Basic_SelectTeamThree;
        public InputAction @SelectTeamFour => m_Wrapper.m_Basic_SelectTeamFour;
        public InputAction @SelectTeamFive => m_Wrapper.m_Basic_SelectTeamFive;
        public InputAction @Pause => m_Wrapper.m_Basic_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Basic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActions set) { return set.Get(); }
        public void SetCallbacks(IBasicActions instance)
        {
            if (m_Wrapper.m_BasicActionsCallbackInterface != null)
            {
                @ShowSelector.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnShowSelector;
                @ShowSelector.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnShowSelector;
                @ShowSelector.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnShowSelector;
                @Click.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnClick;
                @ClickHold.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnClickHold;
                @ClickHold.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnClickHold;
                @ClickHold.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnClickHold;
                @Move.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnMove;
                @Deselect.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnDeselect;
                @Deselect.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnDeselect;
                @Deselect.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnDeselect;
                @CreateTeamOne.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamOne;
                @CreateTeamOne.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamOne;
                @CreateTeamOne.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamOne;
                @CreateTeamTwo.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamTwo;
                @CreateTeamTwo.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamTwo;
                @CreateTeamTwo.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamTwo;
                @CreateTeamThree.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamThree;
                @CreateTeamThree.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamThree;
                @CreateTeamThree.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamThree;
                @CreateTeamFour.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFour;
                @CreateTeamFour.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFour;
                @CreateTeamFour.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFour;
                @CreateTeamFive.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFive;
                @CreateTeamFive.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFive;
                @CreateTeamFive.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCreateTeamFive;
                @SelectTeamOne.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamOne;
                @SelectTeamOne.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamOne;
                @SelectTeamOne.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamOne;
                @SelectTeamTwo.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamTwo;
                @SelectTeamTwo.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamTwo;
                @SelectTeamTwo.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamTwo;
                @SelectTeamThree.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamThree;
                @SelectTeamThree.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamThree;
                @SelectTeamThree.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamThree;
                @SelectTeamFour.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFour;
                @SelectTeamFour.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFour;
                @SelectTeamFour.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFour;
                @SelectTeamFive.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFive;
                @SelectTeamFive.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFive;
                @SelectTeamFive.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnSelectTeamFive;
                @Pause.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_BasicActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ShowSelector.started += instance.OnShowSelector;
                @ShowSelector.performed += instance.OnShowSelector;
                @ShowSelector.canceled += instance.OnShowSelector;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ClickHold.started += instance.OnClickHold;
                @ClickHold.performed += instance.OnClickHold;
                @ClickHold.canceled += instance.OnClickHold;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Deselect.started += instance.OnDeselect;
                @Deselect.performed += instance.OnDeselect;
                @Deselect.canceled += instance.OnDeselect;
                @CreateTeamOne.started += instance.OnCreateTeamOne;
                @CreateTeamOne.performed += instance.OnCreateTeamOne;
                @CreateTeamOne.canceled += instance.OnCreateTeamOne;
                @CreateTeamTwo.started += instance.OnCreateTeamTwo;
                @CreateTeamTwo.performed += instance.OnCreateTeamTwo;
                @CreateTeamTwo.canceled += instance.OnCreateTeamTwo;
                @CreateTeamThree.started += instance.OnCreateTeamThree;
                @CreateTeamThree.performed += instance.OnCreateTeamThree;
                @CreateTeamThree.canceled += instance.OnCreateTeamThree;
                @CreateTeamFour.started += instance.OnCreateTeamFour;
                @CreateTeamFour.performed += instance.OnCreateTeamFour;
                @CreateTeamFour.canceled += instance.OnCreateTeamFour;
                @CreateTeamFive.started += instance.OnCreateTeamFive;
                @CreateTeamFive.performed += instance.OnCreateTeamFive;
                @CreateTeamFive.canceled += instance.OnCreateTeamFive;
                @SelectTeamOne.started += instance.OnSelectTeamOne;
                @SelectTeamOne.performed += instance.OnSelectTeamOne;
                @SelectTeamOne.canceled += instance.OnSelectTeamOne;
                @SelectTeamTwo.started += instance.OnSelectTeamTwo;
                @SelectTeamTwo.performed += instance.OnSelectTeamTwo;
                @SelectTeamTwo.canceled += instance.OnSelectTeamTwo;
                @SelectTeamThree.started += instance.OnSelectTeamThree;
                @SelectTeamThree.performed += instance.OnSelectTeamThree;
                @SelectTeamThree.canceled += instance.OnSelectTeamThree;
                @SelectTeamFour.started += instance.OnSelectTeamFour;
                @SelectTeamFour.performed += instance.OnSelectTeamFour;
                @SelectTeamFour.canceled += instance.OnSelectTeamFour;
                @SelectTeamFive.started += instance.OnSelectTeamFive;
                @SelectTeamFive.performed += instance.OnSelectTeamFive;
                @SelectTeamFive.canceled += instance.OnSelectTeamFive;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public BasicActions @Basic => new BasicActions(this);
    public interface IBasicActions
    {
        void OnShowSelector(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnClickHold(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnDeselect(InputAction.CallbackContext context);
        void OnCreateTeamOne(InputAction.CallbackContext context);
        void OnCreateTeamTwo(InputAction.CallbackContext context);
        void OnCreateTeamThree(InputAction.CallbackContext context);
        void OnCreateTeamFour(InputAction.CallbackContext context);
        void OnCreateTeamFive(InputAction.CallbackContext context);
        void OnSelectTeamOne(InputAction.CallbackContext context);
        void OnSelectTeamTwo(InputAction.CallbackContext context);
        void OnSelectTeamThree(InputAction.CallbackContext context);
        void OnSelectTeamFour(InputAction.CallbackContext context);
        void OnSelectTeamFive(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
